### PR TITLE
replace proc-macro-error dependency

### LINKED ISSUE #23: Update proc-macro-error dependency
build-info-proc currently depends on proc-macro-error, which is no longer maintained. It would be beneficial to migrate to the newer and actively maintained proc-macro-error2 crate.

> $ cargo audit -D warnings $CARGO_AUDIT_ARGS -d ./.cargo-audit-db
    Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
      Loaded 658 security advisories (from ./.cargo-audit-db)
    Updating crates.io index
    Scanning Cargo.lock for vulnerabilities (364 crate dependencies)
Crate:     proc-macro-error
Version:   1.0.4
Warning:   unmaintained
Title:     proc-macro-error is unmaintained
Date:      2024-09-01
ID:        RUSTSEC-2024-0370
URL:       https://rustsec.org/advisories/RUSTSEC-2024-0370
Dependency tree:
proc-macro-error 1.0.4
└── build-info-proc 0.0.34
    └── build-info 0.0.34

### PR DESCRIPTION
**Pull request by kiatweitan**
resolves #23

### CODE REVIEW

**Comment by danielschemmel** [comment]
Thank you for your contribution.

**Comment by holzgeist** [comment]
Hi @danielschemmel,

do you have a time frame for the next release which will contain this change?

**Comment by danielschemmel** [comment]
Release 0.0.39 should contain these changes and be out now.

**Comment by holzgeist** [comment]
awesome, thanks!

**Pull request merged**
